---

- hosts: laptop
  connection: local
  become: true 
  roles:
    - { role: git , tags: git }
    - { role: firefox , tags: firefox }
    - { role: docker , tags: docker }
    - { role: terminator , tags: terminator }
    - { role: misc , tags: misc }
    - { role: zsh , tags: zsh }
    - { role: oh-my-zsh, tags: ohmyz }
    